version: '3'

services:
  jenkins:
    build: .
    container_name: jenkins
    ports:
      - 8080:8080
    volumes:
      - jenkins_tutorial:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock # Importante esta linea, caso contrario no podremos usar docker dentro de docker
volumes:
  jenkins_tutorial: